spring.application.name=university-portal
server.port=${SERVER_PORT:8080}
university.api-url=${UNIVERSITY_API_URL:https://api-university.vercel.app}
university.api-key=${UNIVERSITY_API_KEY:}
university.team-id=${TEAM_ID:01}
university.timeout-seconds=${UPSTREAM_TIMEOUT_SECONDS:8}
server.error.include-message=never
